//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repographer.DataAccess
{
    using System;
    
    public enum NodeTypes : int
    {
        Solution = 1,
        Project = 2,
        Assembly = 3,
        GAC = 4,
        NugetPackage = 5
    }
}
