//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repographer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NodeType
    {
        public NodeType()
        {
            this.Nodes = new HashSet<Node>();
        }
    
        public NodeTypes NodeTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Node> Nodes { get; set; }
    }
}
