//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repographer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public Node()
        {
            this.Out = new HashSet<Relation>();
            this.In = new HashSet<Relation>();
        }
    
        public int NodeID { get; set; }
        public NodeTypes NodeTypeID { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
    
        public virtual NodeType NodeType { get; set; }
        public virtual ICollection<Relation> Out { get; set; }
        public virtual ICollection<Relation> In { get; set; }
    }
}
