//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repographer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relation
    {
        public int RelationID { get; set; }
        public RelationTypes RelationTypeID { get; set; }
        public int FromNodeID { get; set; }
        public int ToNodeID { get; set; }
        public double Weight { get; set; }
    
        public virtual Node From { get; set; }
        public virtual Node To { get; set; }
        public virtual RelationType RelationType { get; set; }
    }
}
